### ISSUE TITLE
docker-compose 启动报错

### ISSUE THREAD

**Issue by kiveno** [cheese-jam/missevanbot#30]
bot_1    | panic: connect to Redis server failed: dial tcp 127.0.0.1:6379: connect: connection refused

#redis-cli
127.0.0.1:379>ping
pong

config.yaml
```
node: "初号机-01"
log: "mebot.log"
level: "debug"
token: "629509fb%7C1653661621%7C2beced90b19110a3"
redis:
  host: "127.0.0.1:6379"
  passwd: "1qaz@WSX"
  db: 0
ownthink:
  appid: ""
muxiaoguo:
  caihongpi: ""
  tianqi: ""
push:
  bark:
    token: ""
  feishu:
    token: ""
admin:
  - 11205
```
